service: tasks-api

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.12
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 30
  environment:
    APP_ENVIRONMENT: ${self:provider.stage}

package:
  exclude:
    - node_modules/**
    
functions:
  API:
    handler: main.handle
    timeout: 10
    memorySize: 512
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: ${env:ALLOWED_ORIGINS}
            maxAge: 60

custom:
  pythonRequirements:
    usePoetry: true
    noDeploy:
      - boto3
      - botocore

plugins:
  - serverless-python-requirements
